#!/usr/bin/env python3
"""Validates an OpenAPI spec against what ApiGen's generator actually reads.

Ground-truth rules reverse-engineered from apiaddicts/apigen.net's
src/Generator (OpenApiUtils.cs, ModelsEntityGenerator.cs,
MappingProfileGenerator.cs, ControllersGenerator.cs), not from what the
example specs merely suggest. See the SKILL.md next to this script's parent
folder for the full rationale per rule.
"""
import json
import os
import sys

CRITICAL = []
WARNING = []
INFO = []


def crit(msg):
    CRITICAL.append(msg)


def warn(msg):
    WARNING.append(msg)


def info(msg):
    INFO.append(msg)


def load_spec(path):
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    if path.lower().endswith((".yml", ".yaml")):
        try:
            import yaml
        except ImportError:
            print(
                "ERROR: PyYAML is not installed. Install it with: pip install pyyaml",
                file=sys.stderr,
            )
            sys.exit(2)
        return yaml.safe_load(text)
    return json.loads(text)


DEAD_ATTR_KEYS = ["ref-model", "items-ref-model", "is-array", "relation-type", "validations"]
DEAD_RELPERSIST_KEYS = [
    "relation-type",
    "join-column",
    "referenced-column",
    "join-table",
    "inverse-join-column",
    "autogenerated",
]
DEAD_PROJECT_KEYS = ["name", "description", "version", "java-properties"]
HTTP_METHODS = ["get", "put", "post", "delete", "options", "head", "patch", "trace"]


def check_project(doc):
    proj = doc.get("x-apigen-project")
    if not isinstance(proj, dict):
        info(
            "x-apigen-project missing: not a critical problem, but 'data-driver' will "
            "not be defined (in-memory persistence by default)."
        )
        return
    driver = proj.get("data-driver")
    if driver is not None and str(driver).lower() not in ("postgresql", "mysql"):
        warn(
            f"x-apigen-project.data-driver = '{driver}' is neither 'postgresql' nor "
            "'mysql' -> silently falls back to in-memory."
        )
    for k in DEAD_PROJECT_KEYS:
        if k in proj:
            info(
                f"x-apigen-project.{k} is present but the generator never reads it "
                "(it uses the standard OpenAPI info.title/info.description instead)."
            )


def iter_attributes(attrs):
    """Yield (label, attr_dict, style) for both list-style and map-style attributes."""
    if isinstance(attrs, list):
        for a in attrs:
            if not isinstance(a, dict):
                continue
            name = a.get("name")
            yield (name or "<no name>", a, "list")
    elif isinstance(attrs, dict):
        for name, a in attrs.items():
            yield (name, a if isinstance(a, dict) else {}, "map")


def check_models(doc):
    components = doc.get("components") or {}
    models = components.get("x-apigen-models")
    if not isinstance(models, dict) or not models:
        crit(
            "x-apigen-models missing or empty under 'components' -> the generator "
            "will produce a placeholder 'Sample' entity instead of your real entities."
        )
        return {}

    for entity_name, entity in models.items():
        if not isinstance(entity, dict):
            crit(f"x-apigen-models.{entity_name} is not a valid object.")
            continue

        attrs = entity.get("attributes")
        if not attrs:
            warn(
                f"x-apigen-models.{entity_name}.attributes missing or empty -> the "
                f"class '{entity_name}' will be generated without properties."
            )
            continue

        for label, a, style in iter_attributes(attrs):
            if style == "list" and not a.get("name"):
                crit(
                    f"x-apigen-models.{entity_name}: a list-style attribute has no "
                    "'name' -> the generator will throw NullReferenceException during generation."
                )
            if not a.get("type"):
                crit(
                    f"x-apigen-models.{entity_name}.{label}: missing 'type' -> the "
                    "generator will throw NullReferenceException/InvalidCastException during generation."
                )
            for k in DEAD_ATTR_KEYS:
                if k in a:
                    hint = (
                        " Use 'items-type' instead of 'ref-model'/'is-array' to "
                        "type arrays/relations."
                        if k in ("ref-model", "is-array", "items-ref-model")
                        else " It is silently ignored."
                    )
                    info(
                        f"x-apigen-models.{entity_name}.{label}.{k} is present "
                        f"but the generator never reads it.{hint}"
                    )
            rp = a.get("relational-persistence") or {}
            if isinstance(rp, dict):
                for k in DEAD_RELPERSIST_KEYS:
                    if k in rp:
                        hint = (
                            " Only 'primary-key: true' matters for autogenerating the id."
                            if k == "autogenerated"
                            else ""
                        )
                        info(
                            f"x-apigen-models.{entity_name}.{label}.relational-persistence.{k} "
                            f"is present but the generator never reads it.{hint}"
                        )
                column = rp.get("column")
                if column and label and column != label:
                    warn(
                        f"x-apigen-models.{entity_name}.{label} looks like an FK "
                        f"(column='{column}' differs from the property name). If the "
                        "referenced entity uses map-style 'attributes' (not "
                        "list), the FK type will fall back to 'long?' without warning -> use "
                        "list style in the referenced entity if you need the actual "
                        "type of its primary key."
                    )
    return models


def check_operation_ids(doc):
    """operationId is a standard OpenAPI field, not x-apigen-*, but ApiGen's
    ControllersGenerator crashes (ArgumentNullException in Humanizer.Pascalize)
    if any operation lacks it -- confirmed by running the CLI directly.
    """
    paths = doc.get("paths") or {}
    for path_name, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        for method in HTTP_METHODS:
            operation = path_item.get(method)
            if not isinstance(operation, dict):
                continue
            if not operation.get("operationId"):
                crit(
                    f"paths.{path_name}.{method} has no 'operationId' -> the "
                    "generator will throw ArgumentNullException (Humanizer.Pascalize) "
                    "when generating the controller. 'operationId' is a standard "
                    "OpenAPI field (not x-apigen-*), but it is mandatory for ApiGen."
                )


def check_tags(doc):
    """OpenApiUtils.TagsByDocPath dedupes tags by name, but ControllersGenerator
    later filters operations with `operation.Value.Tags.Contains(tag.Tag)` using
    the OpenApiTag object itself. When a tag name is only declared inline
    (`operation.tags: [name]`) and never in the document's root `tags:` array,
    Microsoft.OpenApi.Readers does not intern/reuse a single OpenApiTag instance
    across operations -- each operation gets its own distinct object with the
    same Name. `Contains` then only matches by reference, so only ONE operation
    per tag name survives in the generated controller; the rest are silently
    dropped (no error, no warning from ApiGen itself). Confirmed by generating
    and inspecting the controller directly.
    """
    declared = set()
    for t in doc.get("tags") or []:
        if isinstance(t, dict) and t.get("name"):
            declared.add(t["name"])

    usage = {}
    paths = doc.get("paths") or {}
    for path_item in paths.values():
        if not isinstance(path_item, dict):
            continue
        for method in HTTP_METHODS:
            operation = path_item.get(method)
            if not isinstance(operation, dict):
                continue
            for tag_name in operation.get("tags") or []:
                usage[tag_name] = usage.get(tag_name, 0) + 1

    for tag_name, count in usage.items():
        if tag_name in declared:
            continue
        if count >= 2:
            crit(
                f"Tag '{tag_name}' is used in {count} operations but is not "
                "declared in the document's root 'tags' array -> "
                "ApiGen will generate the controller with ONLY ONE of those operations "
                "(the rest are silently dropped, with no error). Add "
                f"'tags: [{{name: {tag_name}}}]' to the OpenAPI root."
            )
        else:
            info(
                f"Tag '{tag_name}' is not declared in the document's root "
                "'tags' array. With a single operation it doesn't fail today, "
                "but if you add another operation with the same tag without declaring it "
                "first, that new operation (or the existing one) will disappear from the "
                "generated controller without warning."
            )


def check_mapping_and_binding(doc, models):
    components = doc.get("components") or {}
    schemas = components.get("schemas") or {}
    model_names = set(models.keys()) if isinstance(models, dict) else set()

    for schema_name, schema in schemas.items():
        if not isinstance(schema, dict):
            continue
        mapping = schema.get("x-apigen-mapping")
        if not mapping:
            continue
        model = mapping.get("model") if isinstance(mapping, dict) else None
        if not model:
            warn(
                f"components.schemas.{schema_name}.x-apigen-mapping has no "
                "'model' -> no AutoMapper mapping will be generated for this DTO."
            )
        elif model not in model_names:
            crit(
                f"components.schemas.{schema_name}.x-apigen-mapping.model = "
                f"'{model}' does not exist in x-apigen-models -> the generated mapping "
                "will reference a nonexistent entity."
            )

    paths = doc.get("paths") or {}
    for path_name, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        binding = path_item.get("x-apigen-binding")
        if not binding:
            warn(
                f"paths.{path_name} has no x-apigen-binding -> its endpoints will be "
                "generated as stubs (NotImplementedException), not as real CRUD."
            )
            continue
        model = binding.get("model") if isinstance(binding, dict) else None
        if not model:
            warn(f"paths.{path_name}.x-apigen-binding has no 'model'.")
        elif model not in model_names:
            crit(
                f"paths.{path_name}.x-apigen-binding.model = '{model}' does not exist "
                "in x-apigen-models -> the generated controller will reference a "
                "nonexistent service and the project will NOT compile."
            )


def section(title, items, icon):
    if not items:
        return
    print(f"\n{icon} {title} ({len(items)})")
    for i, m in enumerate(items, 1):
        print(f"  {i}. {m}")


def main():
    if len(sys.argv) < 2:
        print("Usage: apigen_openapi_check.py <openapi-path.yml|yaml|json>", file=sys.stderr)
        sys.exit(2)

    path = sys.argv[1]
    if not os.path.isfile(path):
        print(f"ERROR: file does not exist: {path}", file=sys.stderr)
        sys.exit(2)

    try:
        doc = load_spec(path)
    except Exception as e:
        print(f"ERROR: could not parse the OpenAPI ({e}).", file=sys.stderr)
        sys.exit(2)

    if not isinstance(doc, dict):
        print(
            "ERROR: the document does not look like a valid OpenAPI (root is not an object).",
            file=sys.stderr,
        )
        sys.exit(2)

    check_project(doc)
    models = check_models(doc)
    check_operation_ids(doc)
    check_tags(doc)
    check_mapping_and_binding(doc, models)

    print(f"ApiGen validation report -- {path}")
    section("CRITICAL -- will prevent correct generation or compilation", CRITICAL, "[X]")
    section("WARNING -- the result will be incomplete/degraded", WARNING, "[!]")
    section("INFO -- properties ignored by the generator", INFO, "[i]")

    if not CRITICAL and not WARNING and not INFO:
        print("\n[OK] No findings -- the spec only uses properties the generator actually reads.")

    print(
        f"\nSummary: {len(CRITICAL)} critical, {len(WARNING)} warning(s), "
        f"{len(INFO)} info."
    )
    sys.exit(1 if CRITICAL else 0)


if __name__ == "__main__":
    main()
