#!/usr/bin/env python3
"""Validates an OpenAPI spec against what ApiGen's generator actually reads.

Ground-truth rules reverse-engineered from apiaddicts/apigen.net's
src/Generator (OpenApiUtils.cs, ModelsEntityGenerator.cs,
MappingProfileGenerator.cs, ControllersGenerator.cs), not from what the
example specs merely suggest. See the SKILL.md next to this script's parent
folder for the full rationale per rule.
"""
import json
import os
import sys

CRITICAL = []
WARNING = []
INFO = []


def crit(msg):
    CRITICAL.append(msg)


def warn(msg):
    WARNING.append(msg)


def info(msg):
    INFO.append(msg)


def load_spec(path):
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    if path.lower().endswith((".yml", ".yaml")):
        try:
            import yaml
        except ImportError:
            print(
                "ERROR: PyYAML no esta instalado. Instalalo con: pip install pyyaml",
                file=sys.stderr,
            )
            sys.exit(2)
        return yaml.safe_load(text)
    return json.loads(text)


DEAD_ATTR_KEYS = ["ref-model", "items-ref-model", "is-array", "relation-type", "validations"]
DEAD_RELPERSIST_KEYS = [
    "relation-type",
    "join-column",
    "referenced-column",
    "join-table",
    "inverse-join-column",
    "autogenerated",
]
DEAD_PROJECT_KEYS = ["name", "description", "version", "java-properties"]
HTTP_METHODS = ["get", "put", "post", "delete", "options", "head", "patch", "trace"]


def check_project(doc):
    proj = doc.get("x-apigen-project")
    if not isinstance(proj, dict):
        info(
            "x-apigen-project ausente: sin problema critico, pero 'data-driver' no "
            "quedara definido (persistencia in-memory por defecto)."
        )
        return
    driver = proj.get("data-driver")
    if driver is not None and str(driver).lower() not in ("postgresql", "mysql"):
        warn(
            f"x-apigen-project.data-driver = '{driver}' no es 'postgresql' ni "
            "'mysql' -> cae silenciosamente a in-memory."
        )
    for k in DEAD_PROJECT_KEYS:
        if k in proj:
            info(
                f"x-apigen-project.{k} esta presente pero el generador nunca lo lee "
                "(usa info.title/info.description del OpenAPI estandar en su lugar)."
            )


def iter_attributes(attrs):
    """Yield (label, attr_dict, style) for both list-style and map-style attributes."""
    if isinstance(attrs, list):
        for a in attrs:
            if not isinstance(a, dict):
                continue
            name = a.get("name")
            yield (name or "<sin name>", a, "list")
    elif isinstance(attrs, dict):
        for name, a in attrs.items():
            yield (name, a if isinstance(a, dict) else {}, "map")


def check_models(doc):
    components = doc.get("components") or {}
    models = components.get("x-apigen-models")
    if not isinstance(models, dict) or not models:
        crit(
            "x-apigen-models ausente o vacio bajo 'components' -> el generador "
            "producira una entidad placeholder 'Sample' en vez de tus entidades reales."
        )
        return {}

    for entity_name, entity in models.items():
        if not isinstance(entity, dict):
            crit(f"x-apigen-models.{entity_name} no es un objeto valido.")
            continue

        attrs = entity.get("attributes")
        if not attrs:
            warn(
                f"x-apigen-models.{entity_name}.attributes ausente o vacio -> la "
                f"clase '{entity_name}' se generara sin propiedades."
            )
            continue

        for label, a, style in iter_attributes(attrs):
            if style == "list" and not a.get("name"):
                crit(
                    f"x-apigen-models.{entity_name}: un atributo en estilo lista no "
                    "tiene 'name' -> el generador lanzara NullReferenceException al generar."
                )
            if not a.get("type"):
                crit(
                    f"x-apigen-models.{entity_name}.{label}: falta 'type' -> el "
                    "generador lanzara NullReferenceException/InvalidCastException al generar."
                )
            for k in DEAD_ATTR_KEYS:
                if k in a:
                    hint = (
                        " Usa 'items-type' en vez de 'ref-model'/'is-array' para "
                        "tipar arrays/relaciones."
                        if k in ("ref-model", "is-array", "items-ref-model")
                        else " Se ignora silenciosamente."
                    )
                    info(
                        f"x-apigen-models.{entity_name}.{label}.{k} esta presente "
                        f"pero el generador nunca lo lee.{hint}"
                    )
            rp = a.get("relational-persistence") or {}
            if isinstance(rp, dict):
                for k in DEAD_RELPERSIST_KEYS:
                    if k in rp:
                        hint = (
                            " Solo 'primary-key: true' importa para autogenerar el id."
                            if k == "autogenerated"
                            else ""
                        )
                        info(
                            f"x-apigen-models.{entity_name}.{label}.relational-persistence.{k} "
                            f"esta presente pero el generador nunca lo lee.{hint}"
                        )
                column = rp.get("column")
                if column and label and column != label:
                    warn(
                        f"x-apigen-models.{entity_name}.{label} parece una FK "
                        f"(column='{column}' distinto del nombre de propiedad). Si la "
                        "entidad referenciada usa 'attributes' en estilo mapa (no "
                        "lista), el tipo de la FK caera a 'long?' sin avisar -> usa "
                        "estilo lista en la entidad referenciada si necesitas el tipo "
                        "real de su primary key."
                    )
    return models


def check_operation_ids(doc):
    """operationId is a standard OpenAPI field, not x-apigen-*, but ApiGen's
    ControllersGenerator crashes (ArgumentNullException in Humanizer.Pascalize)
    if any operation lacks it -- confirmed by running the CLI directly.
    """
    paths = doc.get("paths") or {}
    for path_name, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        for method in HTTP_METHODS:
            operation = path_item.get(method)
            if not isinstance(operation, dict):
                continue
            if not operation.get("operationId"):
                crit(
                    f"paths.{path_name}.{method} no tiene 'operationId' -> el "
                    "generador lanzara ArgumentNullException (Humanizer.Pascalize) "
                    "al generar el controller. 'operationId' es un campo OpenAPI "
                    "estandar (no x-apigen-*), pero es obligatorio para ApiGen."
                )


def check_tags(doc):
    """OpenApiUtils.TagsByDocPath dedupes tags by name, but ControllersGenerator
    later filters operations with `operation.Value.Tags.Contains(tag.Tag)` using
    the OpenApiTag object itself. When a tag name is only declared inline
    (`operation.tags: [name]`) and never in the document's root `tags:` array,
    Microsoft.OpenApi.Readers does not intern/reuse a single OpenApiTag instance
    across operations -- each operation gets its own distinct object with the
    same Name. `Contains` then only matches by reference, so only ONE operation
    per tag name survives in the generated controller; the rest are silently
    dropped (no error, no warning from ApiGen itself). Confirmed by generating
    and inspecting the controller directly.
    """
    declared = set()
    for t in doc.get("tags") or []:
        if isinstance(t, dict) and t.get("name"):
            declared.add(t["name"])

    usage = {}
    paths = doc.get("paths") or {}
    for path_item in paths.values():
        if not isinstance(path_item, dict):
            continue
        for method in HTTP_METHODS:
            operation = path_item.get(method)
            if not isinstance(operation, dict):
                continue
            for tag_name in operation.get("tags") or []:
                usage[tag_name] = usage.get(tag_name, 0) + 1

    for tag_name, count in usage.items():
        if tag_name in declared:
            continue
        if count >= 2:
            crit(
                f"El tag '{tag_name}' se usa en {count} operaciones pero no esta "
                "declarado en el arreglo 'tags' de la raiz del documento -> "
                "ApiGen generara el controller con SOLO UNA de esas operaciones "
                "(las demas se descartan en silencio, sin error). Agrega "
                f"'tags: [{{name: {tag_name}}}]' a la raiz del OpenAPI."
            )
        else:
            info(
                f"El tag '{tag_name}' no esta declarado en el arreglo 'tags' de "
                "la raiz del documento. Con una sola operacion no falla hoy, "
                "pero si agregas otra operacion con el mismo tag sin declararlo "
                "primero, esa nueva operacion (o la existente) desaparecera del "
                "controller generado sin aviso."
            )


def check_mapping_and_binding(doc, models):
    components = doc.get("components") or {}
    schemas = components.get("schemas") or {}
    model_names = set(models.keys()) if isinstance(models, dict) else set()

    for schema_name, schema in schemas.items():
        if not isinstance(schema, dict):
            continue
        mapping = schema.get("x-apigen-mapping")
        if not mapping:
            continue
        model = mapping.get("model") if isinstance(mapping, dict) else None
        if not model:
            warn(
                f"components.schemas.{schema_name}.x-apigen-mapping no tiene "
                "'model' -> no se generara mapeo AutoMapper para este DTO."
            )
        elif model not in model_names:
            crit(
                f"components.schemas.{schema_name}.x-apigen-mapping.model = "
                f"'{model}' no existe en x-apigen-models -> el mapeo generado "
                "referenciara una entidad inexistente."
            )

    paths = doc.get("paths") or {}
    for path_name, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        binding = path_item.get("x-apigen-binding")
        if not binding:
            warn(
                f"paths.{path_name} no tiene x-apigen-binding -> sus endpoints se "
                "generaran como stub (NotImplementedException), no como CRUD real."
            )
            continue
        model = binding.get("model") if isinstance(binding, dict) else None
        if not model:
            warn(f"paths.{path_name}.x-apigen-binding no tiene 'model'.")
        elif model not in model_names:
            crit(
                f"paths.{path_name}.x-apigen-binding.model = '{model}' no existe "
                "en x-apigen-models -> el controller generado referenciara un "
                "servicio inexistente y el proyecto NO compilara."
            )


def section(title, items, icon):
    if not items:
        return
    print(f"\n{icon} {title} ({len(items)})")
    for i, m in enumerate(items, 1):
        print(f"  {i}. {m}")


def main():
    if len(sys.argv) < 2:
        print("Uso: apigen_openapi_check.py <ruta-openapi.yml|yaml|json>", file=sys.stderr)
        sys.exit(2)

    path = sys.argv[1]
    if not os.path.isfile(path):
        print(f"ERROR: no existe el archivo: {path}", file=sys.stderr)
        sys.exit(2)

    try:
        doc = load_spec(path)
    except Exception as e:
        print(f"ERROR: no se pudo parsear el OpenAPI ({e}).", file=sys.stderr)
        sys.exit(2)

    if not isinstance(doc, dict):
        print(
            "ERROR: el documento no parece un OpenAPI valido (raiz no es un objeto).",
            file=sys.stderr,
        )
        sys.exit(2)

    check_project(doc)
    models = check_models(doc)
    check_operation_ids(doc)
    check_tags(doc)
    check_mapping_and_binding(doc, models)

    print(f"Reporte de validacion ApiGen -- {path}")
    section("CRITICO -- impedira generar o compilar correctamente", CRITICAL, "[X]")
    section("ADVERTENCIA -- el resultado sera incompleto/degradado", WARNING, "[!]")
    section("INFORMATIVO -- propiedades ignoradas por el generador", INFO, "[i]")

    if not CRITICAL and not WARNING and not INFO:
        print("\n[OK] Sin hallazgos -- el spec usa solo propiedades que el generador realmente lee.")

    print(
        f"\nResumen: {len(CRITICAL)} critico(s), {len(WARNING)} advertencia(s), "
        f"{len(INFO)} informativo(s)."
    )
    sys.exit(1 if CRITICAL else 0)


if __name__ == "__main__":
    main()
